services:
  windows-lab:
    build: .
    image: msjpq/windows-in-docker:latest
    container_name: windows-lab
    security_opt:
      - apparmor=unconfined
    environment:
      - TZ=Europe/Paris
      - DATA_DIR=/data
      - DEV=1
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
      - /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock:ro
    restart: unless-stopped
