services:
  ubuntu-web:
    build: .
    image: ubuntu-web:latest
    container_name: ubuntu-web-lab
    ports:
      - "6901:6901" # KasmVNC (Web Desktop)
    volumes:
      - .:/home/ubuntuweb/iso-builder
    privileged: true # NÃ©cessaire pour monter des images loop lors de la construction d'ISO
    environment:
      - RESOLUTION=1280x720
