services:
  ubuntu-web-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: ubuntu-web-prod:latest
    container_name: ubuntu-web-prod
    ports:
      - "80:6080" # Port HTTP standard pour la prod
    environment:
      - RESOLUTION=1920x1080
    restart: always
